
package ultimate_idm;

public class dashboard extends javax.swing.JFrame {

    public dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel1.setText("Categories");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FIle Name", "Size", "Status", "Time left", "Transfer Rate", "Last Try Date", "Description"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jMenu3.setText("Tasks");
        jMenu3.setFocusable(false);
        jMenu3.setFont(new java.awt.Font("Bookman Old Style", 1, 13)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem1.setText("Add New Download");
        jMenu3.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem2.setText("Add Batch Download");
        jMenu3.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem3.setText("Add Batch from Clipboard");
        jMenu3.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem4.setText("Run SIte Grabber");
        jMenu3.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem5.setText("Show Drop Target");
        jMenu3.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem6.setText("Export");
        jMenu3.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem7.setText("Import");
        jMenu3.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem8.setText("Exit");
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Bookman Old Style", 1, 13)); // NOI18N

        jMenuItem9.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem9.setText("Stop Download");
        jMenu1.add(jMenuItem9);

        jMenuItem10.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem10.setText("Remove");
        jMenu1.add(jMenuItem10);

        jMenuItem11.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem11.setText("Download Now");
        jMenu1.add(jMenuItem11);

        jMenuItem12.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem12.setText("Re-Download");
        jMenu1.add(jMenuItem12);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Downloads");
        jMenu2.setFont(new java.awt.Font("Bookman Old Style", 1, 13)); // NOI18N

        jMenuItem13.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem13.setText("Pause All");
        jMenu2.add(jMenuItem13);
        jMenuItem13.getAccessibleContext().setAccessibleName("Pause All");

        jMenuItem14.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem14.setText("Stop All");
        jMenu2.add(jMenuItem14);

        jMenuItem15.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem15.setText("Delete All Completed");
        jMenu2.add(jMenuItem15);

        jMenuItem16.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem16.setText("Find");
        jMenu2.add(jMenuItem16);

        jMenuItem17.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem17.setText("Scheduler");
        jMenu2.add(jMenuItem17);

        jMenuItem18.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem18.setText("Start Queue");
        jMenu2.add(jMenuItem18);

        jMenuItem19.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem19.setText("Stop Queue");
        jMenu2.add(jMenuItem19);

        jMenuItem20.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem20.setText("Speed Limiter");
        jMenu2.add(jMenuItem20);

        jMenuItem21.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem21.setText("Options");
        jMenu2.add(jMenuItem21);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("View");
        jMenu4.setFont(new java.awt.Font("Bookman Old Style", 1, 13)); // NOI18N

        jMenuItem22.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem22.setText("Hide Categories");
        jMenu4.add(jMenuItem22);

        jMenuItem23.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem23.setText("Arrange Files");
        jMenu4.add(jMenuItem23);

        jMenuItem24.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem24.setText("Toolbar");
        jMenu4.add(jMenuItem24);

        jMenuItem25.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem25.setText("IDM Tray Icin");
        jMenu4.add(jMenuItem25);

        jMenuItem26.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem26.setText("Customize URL List");
        jMenu4.add(jMenuItem26);

        jMenuItem27.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem27.setText("Language");
        jMenu4.add(jMenuItem27);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Help");
        jMenu5.setFont(new java.awt.Font("Bookman Old Style", 1, 13)); // NOI18N

        jMenuItem28.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem28.setText("Help Contents");
        jMenu5.add(jMenuItem28);

        jMenuItem29.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem29.setText("Tutorials");
        jMenu5.add(jMenuItem29);

        jMenuItem30.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem30.setText("Scheduler & queue");
        jMenu5.add(jMenuItem30);

        jMenuItem31.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem31.setText("Grabber Help");
        jMenu5.add(jMenuItem31);

        jMenuItem32.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem32.setText("Tip of the Day");
        jMenu5.add(jMenuItem32);

        jMenuItem33.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem33.setText("IDM Hoem Page");
        jMenu5.add(jMenuItem33);

        jMenuItem34.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem34.setText("Contact Support");
        jMenu5.add(jMenuItem34);

        jMenuItem35.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem35.setText("Check for Updates");
        jMenu5.add(jMenuItem35);

        jMenuItem36.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem36.setText("About IDM");
        jMenu5.add(jMenuItem36);

        jMenuItem37.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jMenuItem37.setText("Tell a friend");
        jMenu5.add(jMenuItem37);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
